require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.extras.tokyonight"
spec "user.extras.osaka"
spec "user.extras.catppuccin"
-- spec "user.exus"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
-- spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.harpoon"
-- spec "user.neotest"
spec "user.autopairs"
spec "user.neogit"
spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.extras.bqf"
spec "user.extras.colorizer"
spec "user.extras.copilot"
spec "user.extras.dressing"
spec "user.extras.fidget"
spec "user.extras.lab"
-- spec "user.extras.modicator"
-- spec "user.extras.neotab"
spec "user.extras.oil"
spec "user.extras.tabby"
spec "user.extras.ufo"
spec "user.extras.flash"
spec "user.extras.surround"
spec "user.extras.notify"
spec "user.extras.noice"
spec "user.extras.bigfile"
spec "user.extras.navbuddy"
-- spec "user.extras.neoscroll"
-- spec "user.extras.incline"
require "user.lazy"
